### ISSUE TITLE
Conflict with the Corpse mod. 

### ISSUE THREAD

**Issue by ClockwerkKaiser** [Create-Additions/CreateAutomated#3]
When installed along side the Corpse mod, the Corpse becomes unable to be interacted with. 

This only happens when Create Automated is present as of version 1.2.0. The problem persists with v1.2.1.

Version 1.1.0 doesn't cause this issue.

There is no error thrown in the logs.

**Comment by kotakotik22** [comment]
that happens because of the new node movement config, i messed with entity interaction and broke something

**Comment by kotakotik22** [comment]
temporary fix would be to change create's spawner movement settings to something other than No_pickup
