### ISSUE TITLE
Crash when loading on server

### ISSUE THREAD

**Issue by Jerome226** [Create-Additions/CreateAutomated#4]
[crash-2021-08-01_18.24.51-fml.txt](https://github.com/Create-Additions/CreateAutomated/files/6913704/crash-2021-08-01_18.24.51-fml.txt)

**Comment by kotakotik22** [comment]
will be fixed in the next version. for now you can use this jar on your server (only required on the servers, players can use whatever)
https://cdn.discordapp.com/attachments/861376036331192330/871411495622283274/createautomated-1.16.5-1.2.1a.jar

**Comment by Jerome226** [comment]
Thanks!
