### ISSUE TITLE
Crashing on startup using 1.4.0 on server

### ISSUE THREAD

**Issue by lebagvondouche** [Create-Additions/CreateAutomated#7]
Crashlog here: https://pastebin.com/zWrg4eDn

Works on the client but not on the server.

**Comment by kotakotik22** [comment]
fixed in 10b9b25
https://www.curseforge.com/minecraft/mc-mods/create-automated/files/3427185

**Comment by lebagvondouche** [comment]
Thanks for the fast support dude!
